### ISSUE TITLE
Metadata clarification

### ISSUE THREAD

**Issue by clbarnes** [david-hoffman/FIB-SEM-Aligner#1]
- In `readfibsem.m`, there is a parsed date (`SWDate`) in an ambiguous format `??/??/YYYY`, rather than the unambiguous international standard `YYYY-MM-DD`. Is it `MM/DD` (non-military American), or `DD/MM` (most of the rest of the world)?
- `MillingPIDMeasured` is an enum with documented meanings of 0 and 1. Are there any other values it can take? I believe I have a `.dat` file with a 3 in that position.

**Comment by david-hoffman** [comment]
Sorry, this isn’t an actively maintained repo. You should reach out to C. Shan Xu at Janelia research campus

**Comment by clbarnes** [comment]
Would it be possible to add a README with that information?
